services:
  app:
    build: .
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
#    develop:
#      watch:
#        - action: rebuild
#          path: ./src
#          target: /app/src
#          ignore:
#            - node_modules/
#        - action: rebuild
#          path: package.json